# Generated by Django 5.0.4 on 2024-05-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_rename_director_movie_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user',
            new_name='director',
        ),
    ]
