# Generated by Django 5.0.4 on 2024-04-27 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='updated_at',
        ),
    ]
