# Generated by Django 5.0.4 on 2024-05-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0002_alter_show_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
