# Generated by Django 5.0.4 on 2024-05-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0005_alter_show_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
