# Generated by Django 5.0.4 on 2024-05-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0006_alter_show_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
